name: textgen
services:
  fastapi:
    public: true
    image: emekaboris/text_generation_with_pytorch:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 5000m
      memory: 4280Mi