name: textgen
services:
  Textgen:
    public: true
    image: emekaboris/text_generation_with_pytorch:latest
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 1000m
      memory: 3Gi
